[base]
package = super_mario_bros
env_name = SuperMarioBros-1-1-v3
policy_name = Policy
rnn_name = Recurrent
vec = multiprocessing

[train]
total_timesteps = 1_000_000
num_envs = 96
num_workers = 6
env_batch_size = 32

; zero_copy = False
; update_epochs = 3
; gamma = 0.998


batch_size = 24576
minibatch_size = 6144

; compile = True
; learning_rate = 2.0e-4

[sweep.metric]
goal = maximize
name = score 
min = 0
max = None

[sweep.train.total_timesteps]
distribution = log_normal
min = 1e5
max = 1e8
mean = 1e6
scale = auto
