[base]
package = smb
env_name = SuperMarioBros-1-1-v1
policy_name = Policy
; rnn_name = Recurrent
; vec = multiprocessing


[vec]
num_envs = 6

[train]
total_timesteps = 1_000_000
batch_size = auto
bptt_horizon = 64
minibatch_size = 384

; num_envs = 64
; num_workers = 4
env_batch_size = 6

; zero_copy = False
; update_epochs = 3
; gamma = 0.998


; batch_size = 32768


; minibatch_size = 8192

; compile = True
; compile_mode = max-autotune
; compile_fullgraph = True

; learning_rate = 2.0e-4

[sweep.train.total_timesteps]
distribution = log_normal
min = 1e5
max = 1e8
mean = 1e6
scale = auto


[sweep.vec.num_envs]
; distribution = uniform_pow2
; distribution = int_uniform
; min = 1
; max = 6
; mean = 3
; scale = auto

[sweep.train.minibatch_size]
distribution = uniform_pow2
min = 96
max = 312  # #envs * bptt_horizon
mean = 192
scale = auto

; [sweep.metric]
; goal = maximize
; name = score 
; min = 0
; max = None

; [sweep.train.total_timesteps]
; distribution = log_normal
; min = 1e5
; max = 1e8
; mean = 1e6
; scale = auto
